# Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

## What is an array?
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [ ]:
##initially Lets import numpy
import numpy as np 

In [4]:
arr_list=[1,3,5,9]
a=np.array(arr_list)
print(a)

[1 3 5 9]


In [5]:
a.shape

(4,)

In [11]:
a=[1,2,3,5,6]
b=[4,5,6,8,9]
c=[7,8,9,7,5]
arr=np.array([a,b,c])
arr

array([[1, 2, 3, 5, 6],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 7, 5]])

In [12]:
arr.shape


(3, 5)

# Reshaping

In [13]:
a=arr.reshape(5,3)

array([[1, 2, 3],
       [5, 6, 4],
       [5, 6, 8],
       [9, 7, 8],
       [9, 7, 5]])

# Indexing 

In [19]:
a=[1,2,3,5,6]
b=[4,5,6,8,9]
c=[7,8,9,7,5]
arr=np.array([a,b,c])
arr

array([[1, 2, 3, 5, 6],
       [4, 5, 6, 8, 9],
       [7, 8, 9, 7, 5]])

In [20]:
arr[0]

array([1, 2, 3, 5, 6])

In [21]:
arr[0,4]

6

In [22]:
arr[2,4]

5

In [24]:
arr[1:,2:]

array([[6, 8, 9],
       [9, 7, 5]])

In [25]:
arr[1:,2:]

array([[6, 8, 9],
       [9, 7, 5]])

In [27]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[5:]=0
a

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 0])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [42]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [44]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

# Random numbers

In [57]:
np.linspace(1,10,50)


array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [47]:
np.random.rand(4,4)

array([[0.47481751, 0.83536422, 0.56937961, 0.33203903],
       [0.72903945, 0.58831513, 0.74081911, 0.7471493 ],
       [0.16219179, 0.29318671, 0.7374427 , 0.07643535],
       [0.81939645, 0.47602492, 0.74660611, 0.87082035]])

In [49]:
np.random.randn(10)

array([-0.44172979,  0.38640433, -0.21036494,  0.20499008, -0.09244278,
        0.17248515,  1.11675262,  1.92971538,  0.27966576,  0.73238435])

In [54]:
arr=np.random.randint(0,100,10).reshape(5,2)
arr

array([[21, 75],
       [81, 11],
       [23, 19],
       [78, 81],
       [81, 16]])

# Operations

In [61]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr.min()

1

In [63]:
arr.max()

9

In [64]:
arr>2

array([False, False,  True,  True,  True,  True,  True,  True,  True])

In [65]:
arr<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [68]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
arr//2

array([0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

In [67]:
arr*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [70]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [71]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [72]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [73]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

# sorting

In [77]:
#genral sorting
b=np.random.randint(1,100,10)
print(b)
np.sort(b)

[61 11 80 20 21 85 74 41 90 75]


array([11, 20, 21, 41, 61, 74, 75, 80, 85, 90])

In [80]:
#argsort(indices sorting)
arr=[90,56,89,67,56]
np.argsort(arr)

array([1, 4, 3, 2, 0], dtype=int64)

In [81]:
#lexsort()
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [82]:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [84]:
##searchsorteed(Find indices where elements should be inserted to maintain order.)
np.searchsorted([1,2,3,4,5], 3)

2

In [85]:
np.searchsorted([1,2,3,4,5], 3, side='right')

3

In [86]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int64)

# concatenate arrays

In [88]:
a = np.array([1, 2, 9])
b = np.array([5, 6, 9])
np.concatenate((a, b))

array([1, 2, 9, 5, 6, 9])

In [91]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [93]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

# stacks

In [95]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [96]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [97]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# How to get unique items and counts?

In [99]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


# How to reverse an array?

In [100]:
##Reversing a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [101]:
##Reversing a 2D array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
